### ISSUE TITLE
Map parsing for CrystalIsles and EbenusAstrum fail

### ISSUE THREAD

**Issue by coldino** [arkutils/Purlovia#86]
In order to add these map mods we need to fix parsing for them.

Example error:
```log
INFO:automate.exporter:Extracting Wiki:Map in mod 916417001 'Ebenus Astrum'
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Mods/EbenusAstrum
ERROR:automate.run:Caught exception during automation run. Aborting.
Traceback (most recent call last):
  File "D:\Work\Gms\Ark\Purlovia\automate\run.py", line 197, in run
    exporter.perform()
  File "D:\Work\Gms\Ark\Purlovia\automate\exporter.py", line 105, in perform
    self._perform_export()
  File "D:\Work\Gms\Ark\Purlovia\automate\exporter.py", line 170, in _perform_export
    stage.extract_mod(root_path, modid)
  File "D:\Work\Gms\Ark\Purlovia\export\wiki\stage_maps.py", line 79, in extract_mod
    self._extract_and_save(version, path, directory_name, levels, known_persistent=f'{directory}/{selectable_maps[0]}')
  File "D:\Work\Gms\Ark\Purlovia\export\wiki\stage_maps.py", line 91, in _extract_and_save
    intermediate = self._gather_data_from_levels(levels, known_persistent=known_persistent)
  File "D:\Work\Gms\Ark\Purlovia\export\wiki\stage_maps.py", line 158, in _gather_data_from_levels
    helper = find_gatherer_for_export(export)
  File "D:\Work\Gms\Ark\Purlovia\export\wiki\maps\gathering.py", line 708, in find_gatherer_for_export
    parents = set(find_parent_classes(export, include_self=True))
  File "D:\Work\Gms\Ark\Purlovia\ue\hierarchy.py", line 126, in find_parent_classes
    parent_name = get_parent_fullname(export)
  File "D:\Work\Gms\Ark\Purlovia\ue\tree.py", line 78, in get_parent_fullname
    parent = export.asset.loader.load_class(parent_fullname)
  File "D:\Work\Gms\Ark\Purlovia\ue\loader.py", line 412, in load_class
    asset = self.load_asset(assetname, quiet=quiet)
  File "D:\Work\Gms\Ark\Purlovia\ue\loader.py", line 451, in load_asset
    self._load_asset(assetname, quiet=quiet, cache_result=cache_result)
  File "D:\Work\Gms\Ark\Purlovia\ue\loader.py", line 479, in _load_asset
    mem, ext = self.load_raw_asset(assetname)
  File "D:\Work\Gms\Ark\Purlovia\ue\loader.py", line 445, in load_raw_asset
    raise AssetNotFound(name)
ue.loader.AssetNotFound: Asset /Game/PrimalEarth/Sound/AmbientSoundActors/RedwoodAmbientSound_Blueprint_Large not found
```

**Comment by alex4401** [comment]
Should be fixed in fb4cd288ee2dfbcecb590df045cae17777dd0482.
