### ISSUE TITLE
Add mod 833379388 "Pugnacia Dinos"

### ISSUE THREAD

**Issue by coldino** [arkutils/Purlovia#88]
This mod currently does not run through Purlovia cleanly. First error is in `processing/stage_spawn_maps.py`:

```py
Traceback (most recent call last):
  File "D:\Work\Gms\Ark\Purlovia\automate\run.py", line 197, in run
    exporter.perform()
  File "D:\Work\Gms\Ark\Purlovia\automate\exporter.py", line 105, in perform
    self._perform_export()
  File "D:\Work\Gms\Ark\Purlovia\automate\exporter.py", line 170, in _perform_export
    stage.extract_mod(root_path, modid)
  File "D:\Work\Gms\Ark\Purlovia\processing\stage_spawn_maps.py", line 49, in extract_mod
    self._game_mod_generate_svgs(modid, mod_data['name'])
  File "D:\Work\Gms\Ark\Purlovia\processing\stage_spawn_maps.py", line 130, in _game_mod_generate_svgs
    data_groups, data_swaps = self._get_spawning_groups(modid, is_game_mod=True)
  File "D:\Work\Gms\Ark\Purlovia\processing\stage_spawn_maps.py", line 96, in _get_spawning_groups
    fix_up_groups(data['spawngroups'])
  File "D:\Work\Gms\Ark\Purlovia\processing\spawn_maps\swaps.py", line 7, in fix_up_groups
    for entry in container['entries']:
KeyError: 'entries'
```

**Comment by alex4401** [comment]
Should be fixed in 6206d52640a0ab7ecbc399f789198e7a4ae72f30.
